# smashlet.py
#
# Combines README section fragments into the root-level README.md.
# Sources come from `*.md` files in this directory, sorted by filename.

import smash

INPUT_GLOB = "*.md"


def run(context):
    files = sorted(context["inputs"])
    if not files:
        smash.log("No README sections found.", level="warn")
        return 0

    contents = smash.read_text_files(files)
    result = (
        "<!-- AUTO-GENERATED BY content/readme_parts/smashlet.py -->\n\n"
        + "\n\n".join(contents).strip()
        + "\n"
    )

    destination = smash.resolve("/../README.md", context)
    changed = smash.write_output_if_changed(destination, result, context)

    if changed:
        smash.log(f"✅ {destination} updated from {len(files)} sections.")
        return 1

    smash.log(f"ℹ️ {destination} already up to date.")
    return 0
